## Colors configuration
[colors.primary]
background = "#181818"
foreground = "#f3d58e"

[colors.normal]
black   = "#181818"
red     = "#CF9320"
green   = "#D79921"
yellow  = "#D9A52E"
blue    = "#D9A62E"
magenta = "#E1AB2E"
cyan    = "#E2AC2E"
white   = "#f3d58e"

[colors.bright]
black   = "#aa9563"
red     = "#CF9320"
green   = "#D79921"
yellow  = "#D9A52E"
blue    = "#D9A62E"
magenta = "#E1AB2E"
cyan    = "#E2AC2E"
white   = "#f3d58e"
