## Colors configuration
[colors.primary]
background = "#0f1116"
foreground = "#e9e4cf"

[colors.normal]
black   = "#0f1116"
red     = "#615E53"
green   = "#8F7534"
yellow  = "#DCA930"
blue    = "#FFCC30"
magenta = "#A58E55"
cyan    = "#B0A88B"
white   = "#e9e4cf"

[colors.bright]
black   = "#a39f90"
red     = "#615E53"
green   = "#8F7534"
yellow  = "#DCA930"
blue    = "#FFCC30"
magenta = "#A58E55"
cyan    = "#B0A88B"
white   = "#e9e4cf"
