## Colors configuration
[colors.primary]
background = "#1e1c1c"
foreground = "#dfd7c6"

[colors.normal]
black   = "#1e1c1c"
red     = "#948B77"
green   = "#A1967E"
yellow  = "#9D9882"
blue    = "#A79C83"
magenta = "#B5A98D"
cyan    = "#C8B999"
white   = "#dfd7c6"

[colors.bright]
black   = "#9c968a"
red     = "#948B77"
green   = "#A1967E"
yellow  = "#9D9882"
blue    = "#A79C83"
magenta = "#B5A98D"
cyan    = "#C8B999"
white   = "#dfd7c6"
