## Colors configuration
[colors.primary]
background = "#101c22"
foreground = "#e2e5eb"

[colors.normal]
black   = "#101c22"
red     = "#61738E"
green   = "#7B9DB9"
yellow  = "#8EABB5"
blue    = "#DCC79B"
magenta = "#82A3C1"
cyan    = "#99ABC6"
white   = "#e2e5eb"

[colors.bright]
black   = "#9ea0a4"
red     = "#61738E"
green   = "#7B9DB9"
yellow  = "#8EABB5"
blue    = "#DCC79B"
magenta = "#82A3C1"
cyan    = "#99ABC6"
white   = "#e2e5eb"
