## Colors configuration
[colors.primary]
background = "#191c24"
foreground = "#c0d2dc"

[colors.normal]
black   = "#191c24"
red     = "#3E5A81"
green   = "#5B7192"
yellow  = "#6C8DAE"
blue    = "#7AABC4"
magenta = "#B08482"
cyan    = "#9B96AC"
white   = "#c0d2dc"

[colors.bright]
black   = "#86939a"
red     = "#3E5A81"
green   = "#5B7192"
yellow  = "#6C8DAE"
blue    = "#7AABC4"
magenta = "#B08482"
cyan    = "#9B96AC"
white   = "#c0d2dc"
