# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/ArchWaveMonoInvertedThumb.png'

# Special
background='#121212'
foreground='#f3f3f3'
cursor='#f3f3f3'

# Colors
color0='#121212'
color1='#CACACA'
color2='#D8D8D8'
color3='#E4E4E4'
color4='#ECECEC'
color5='#F2F2F2'
color6='#F5F5F5'
color7='#f3f3f3'
color8='#aaaaaa'
color9='#CACACA'
color10='#D8D8D8'
color11='#E4E4E4'
color12='#ECECEC'
color13='#F2F2F2'
color14='#F5F5F5'
color15='#f3f3f3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
