# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/ign_dudeOnBuilding2.png'

# Special
background='#191c24'
foreground='#c0d2dc'
cursor='#c0d2dc'

# Colors
color0='#191c24'
color1='#3E5A81'
color2='#5B7192'
color3='#6C8DAE'
color4='#7AABC4'
color5='#B08482'
color6='#9B96AC'
color7='#c0d2dc'
color8='#86939a'
color9='#3E5A81'
color10='#5B7192'
color11='#6C8DAE'
color12='#7AABC4'
color13='#B08482'
color14='#9B96AC'
color15='#c0d2dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
