# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/gruvbox_void_linux.png'

# Special
background='#0f1116'
foreground='#e9e4cf'
cursor='#e9e4cf'

# Colors
color0='#0f1116'
color1='#615E53'
color2='#8F7534'
color3='#DCA930'
color4='#FFCC30'
color5='#A58E55'
color6='#B0A88B'
color7='#e9e4cf'
color8='#a39f90'
color9='#615E53'
color10='#8F7534'
color11='#DCA930'
color12='#FFCC30'
color13='#A58E55'
color14='#B0A88B'
color15='#e9e4cf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
