# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/rubiks-cube.png'

# Special
background='#1e1c1c'
foreground='#dfd7c6'
cursor='#dfd7c6'

# Colors
color0='#1e1c1c'
color1='#948B77'
color2='#A1967E'
color3='#9D9882'
color4='#A79C83'
color5='#B5A98D'
color6='#C8B999'
color7='#dfd7c6'
color8='#9c968a'
color9='#948B77'
color10='#A1967E'
color11='#9D9882'
color12='#A79C83'
color13='#B5A98D'
color14='#C8B999'
color15='#dfd7c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
