# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/us3p54j3ksn61.jpg'

# Special
background='#212534'
foreground='#cad3d8'
cursor='#cad3d8'

# Colors
color0='#212534'
color1='#8FB8B5'
color2='#B6B9B8'
color3='#EBB89F'
color4='#F9B1A3'
color5='#CACAB8'
color6='#91BBCB'
color7='#cad3d8'
color8='#8d9397'
color9='#8FB8B5'
color10='#B6B9B8'
color11='#EBB89F'
color12='#F9B1A3'
color13='#CACAB8'
color14='#91BBCB'
color15='#cad3d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
